copy:
	 scp -r ./* ubuntu@10.21.0.16:/home/ubuntu/projects/enrollmentzatsepinaviktoria
	 scp -r ./.env ubuntu@10.21.0.16:/home/ubuntu/projects/enrollmentzatsepinaviktoria




#     https://unix-1808.usr.yandex-academy.ru/actuator/info

#     https://unix-1808.usr.yandex-academy.ru/swagger-ui/index.html